// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfFwvqIxFFG-URJZJNHVQCbueIGNTepqc',
    appId: '1:330012628255:web:c24f7b138351a8e543cc2a',
    messagingSenderId: '330012628255',
    projectId: 'feed-me-34958',
    authDomain: 'feed-me-34958.firebaseapp.com',
    storageBucket: 'feed-me-34958.appspot.com',
    measurementId: 'G-NRQMJV6Q80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkNrrqh0ndzEvCDDXemFYcmbvORBRCnw0',
    appId: '1:330012628255:android:42a36c18cb66ddd343cc2a',
    messagingSenderId: '330012628255',
    projectId: 'feed-me-34958',
    storageBucket: 'feed-me-34958.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6UfzVwyVNcCuLD-QVHkv245zueFHINIc',
    appId: '1:330012628255:ios:9870dec59bb4eb0543cc2a',
    messagingSenderId: '330012628255',
    projectId: 'feed-me-34958',
    storageBucket: 'feed-me-34958.appspot.com',
    iosBundleId: 'com.sheershbhatnagar.myMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6UfzVwyVNcCuLD-QVHkv245zueFHINIc',
    appId: '1:330012628255:ios:5718fb4f8cb9039043cc2a',
    messagingSenderId: '330012628255',
    projectId: 'feed-me-34958',
    storageBucket: 'feed-me-34958.appspot.com',
    iosBundleId: 'com.sheershbhatnagar.myMeal.RunnerTests',
  );
}
